name: build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        board: ["ESP32 Dev Module"]
        include:
          - board: "ESP32 Dev Module"
            platform: "esp32:esp32"
            fqbn: "esp32:esp32:esp32"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1.1.1

      - name: Install Board Platform
        run: |
          arduino-cli core update-index
          arduino-cli core install ${{ matrix.platform }}

      - name: Install FastLED Library
        run: arduino-cli lib install FastLED

      - name: Compile Sketch
        run: arduino-cli compile --fqbn ${{ matrix.fqbn }} Arduino/LEDstream_esp32/LEDstream_esp32.ino
